version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["87:4a:b6:99:3a:e2:71:31:9a:3b:55:e2:b3:c2:5d:32"] # You can get this ID in the section where you registered the SSH Key
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible # install the dependencies needed for your playbook
      - run:
          name: Configure server
          command: |
            ansible-playbook -i playbook.yml

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure
